# Used for production

services:
  fe-prod:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10000:3000'
    environment:
      - AUTH_API_BASE_URL='https://fleet-docs.cybermicroservices.com/api'