# Used for production

services:
  fe-prod:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL='https://fleet-docs.cybermicroservices.com/api'
    ports:
      - '10000:3000'